name: mp_opt 
channels:
  - anaconda
  #- quantopian
  #- developer
dependencies:
  - python=3.5.1
  - pandas=0.18.1
  - flask=0.11.1
  - xlrd=1.0.0
  - nose=1.3.7
  - configobj=5.0.6
  - mysql-connector-python=2.0.4
  - scipy=0.18.1
  - numpy=1.11.1
  - pip:
    - redis==2.10.5
    - rq==0.6.0
    - pandas_datareader==0.2.1
    - pymysql==0.7.9