name: dl-py2.7 
channels:
  - anaconda
dependencies:
  - python=2.7.13
  - pandas=0.18.1
  - flask=0.11.1
  - xlrd=1.0.0
  - nose=1.3.7
  - configobj=5.0.6
  - mysql-connector-python=2.0.4
  - scipy=0.18.1
  - numpy=1.11.1
  - theano
  - pip:
    - redis==2.10.5
    - rq==0.6.0
    - pandas_datareader==0.2.1
    - pymysql==0.7.9
    - jupyter
    - pdbpp
