name: mp_opt 
channels:
  - anaconda
  #- quantopian
  #- developer
dependencies:
  - nomkl
  - python=3.5.1
  - pandas=0.18.1
  - flask=0.11.1
  - gunicorn=19.1.0
  - xlrd=1.0.0
  - nose=1.3.7
  - configobj=5.0.6
  - mysql-connector-python=2.0.4
  - scipy=0.18.1
  - numpy=1.11.1
  - pip:
    - flask-sqlalchemy==2.1
    - flask-migrate==1.8.1
    - redis==2.10.5
    - rq==0.6.0
    - pandas_datareader==0.2.1
    - inflection==0.3.1
    - flask-restful==0.3.5
    - pymysql==0.7.9
    - CPython==3.6
